version: '3.8'

services:
  app:
    build: .
    container_name: movixpress-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/movixpress?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - db
    networks:
      - movixpress-net
    restart: always

  db:
    image: mysql:8.0
    container_name: movixpress-db
    environment:
      - MYSQL_DATABASE=movixpress
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - movixpress-net
    restart: always
    command: --default-authentication-plugin=mysql_native_password

networks:
  movixpress-net:
    name: movixpress-net
    driver: bridge

volumes:
  mysql_data:
    name: movixpress-mysql-data